### PR TITLE
Enable/Disable Org, User. Add --enable option for create org.

### PR DESCRIPTION
**Pull request by anusuyar**
1. Enable/Disable Org which is already created (via 'vcd org update <org_name>' command)
2. Add new option '--enable' to enable org during creation.
3. Enable/disable user which was already created. (via 'vcd user update <user_name>' command)

### CODE REVIEW

**Comment by anusuyar** [comment]
This change is [Reviewable](https://reviewable.io/reviews/anusuyar/pyvcloud/6)

**Comment by pacogomez** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/system.py, line 57 at r1](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Y3Kb6A6TYrxAVeZBD:-L-Y3Kb6A6TYrxAVeZBE:bmyuu5d) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2f34b61839081fa2cf7fffd286bc7c523e5e1e4c/pyvcloud/vcd/system.py#L57)):*
> ```Python
>             org_params)
> 
>     def update_org(self, org_name, is_enabled=None):
> ```

This method should be located in the Org class, as it applies to an organization. System class should only be responsible for creating/delete and org, while Org should have instance methods to work with the organization.

---

*[pyvcloud/vcd/system.py, line 91 at r1](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Y3zMtORM19ayKi23u:-L-Y3zMtORM19ayKi23v:b-j6mon0) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2f34b61839081fa2cf7fffd286bc7c523e5e1e4c/pyvcloud/vcd/system.py#L91)):*
> ```Python
>     def get_admin_org_href(org):
>         return org.get('href').replace('/api/org/',
>                                        '/api/admin/org/')
> ```

This method should be in the Org class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6)*

**Comment by anusuyar** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[pyvcloud/vcd/system.py, line 57 at r1](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Y3Kb6A6TYrxAVeZBD:-L-YyccYl7i78Jg2qMnY:b-896fix) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2f34b61839081fa2cf7fffd286bc7c523e5e1e4c/pyvcloud/vcd/system.py#L57)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

This method should be located in the Org class, as it applies to an organization. System class should only be responsible for creating/delete and org, while Org should have instance methods to work with the organization.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/system.py, line 91 at r1](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Y3zMtORM19ayKi23u:-L-Yy59wTsBkDPeuBhqG:b9w0wb7) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2f34b61839081fa2cf7fffd286bc7c523e5e1e4c/pyvcloud/vcd/system.py#L91)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

This method should be in the Org class
</blockquote></details>

I moved it to utils.py as it is used in both System and Org class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6)*

**Comment by sahithi** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[tests/vcd_user.py, line 51 at r2](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZXKhHxqthvqjeOjbR:-L-ZXKhHxqthvqjeOjbS:b-1brvnd) ([raw file](https://github.com/anusuyar/pyvcloud/blob/4a5d8ad610183922f0960df5e3bd3a8f215aece9/tests/vcd_user.py#L51)):*
> ```Python
>         self.create_user(user_name, True)
>         updated_user = self.update_user(user_name, False)
>         self.assertFalse(updated_user['IsEnabled'])
> ```

updated_user is the task returned by api call, right? How does updated_user['IsEnabled'] return boolean? Am I missing something :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6)*

**Comment by rocknes** [comment]
Reviewed 1 of 4 files at r1, 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 495 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Zg41JK-xcZzdeUZuI:-L-Zg41JK-xcZzdeUZuJ:bq15u1d) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/pyvcloud/vcd/org.py#L495)):*
> ```Python
>                 user['IsEnabled'] = E.IsEnabled(is_enabled)
> 
>         return self.client.put_resource(user.get('href'), user,
> ```

If the above if checks have failed, we would be doing an unnecessary PUT call, we should avoid that.

---

*[pyvcloud/vcd/org.py, line 650 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZgGnYIFMAAoQPc7dR:-L-ZgGnYIFMAAoQPc7dS:b-6asrdl) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/pyvcloud/vcd/org.py#L650)):*
> ```Python
>                 org_resource['IsEnabled'] = E.IsEnabled(is_enabled)
> 
>         return self.client.put_resource(org_href, org_resource,
> ```

Same as the comment above for update_user, we shouldn't be initiating a no-op PUT request

---

*[pyvcloud/vcd/system.py, line 91 at r1](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Y3zMtORM19ayKi23u:-L-Zh1tpgvnex5Zcoj9M:b-z0rboi) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2f34b61839081fa2cf7fffd286bc7c523e5e1e4c/pyvcloud/vcd/system.py#L91)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I moved it to utils.py as it is used in both System and Org class.
</blockquote></details>

I think we should a more generic version of the function. Something like get_admin_href() which can take any href, replace /api/ to /api/admin/

---

*[pyvcloud/vcd/utils.py, line 60 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZhlDdspn6gk1Go45z:-L-ZhlDelQRK5PnJFQK0:b-ea8ndv) ([raw file](https://github.com/anusuyar/pyvcloud/blob/a3e991fdbd806d23fe8f385d07d362c68ae5eeb6/pyvcloud/vcd/utils.py#L60)):*
> ```Python
>         result['is_enabled'] = bool(vdc.IsEnabled)
>     if hasattr(vdc, 'AvailableNetworks') and \
>        hasattr(vdc.AvailableNetworks, 'Network'):
> ```

Probably you would want to run flake8 from command line on this file. I think the added indentation will trigger a warning.

---

*[pyvcloud/vcd/utils.py, line 323 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZhvcJ3XNSVXpQm8Z0:-L-ZhvcJ3XNSVXpQm8Z1:bwxvsej) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/pyvcloud/vcd/utils.py#L323)):*
> ```Python
> 
> 
> def get_admin_org_href(org):
> ```

As I stated earlier we should have a more generic version of this function. Otherwise the current form of the function belongs to Org.py as pointed out by Paco.

---

*[tests/vcd_org.py, line 1 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZiHfNT7ovOeBNxCx7:-L-ZiHfNT7ovOeBNxCx8:b-6fbvc7) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_org.py#L1)):*
> ```Python
> import unittest
> ```

Shouldn't we add the vmware copyright headers to test files too?

---

*[tests/vcd_org.py, line 16 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZiXz7R0e11blH1Bnx:-L-ZiXz7R0e11blH1Bny:b-nrrqmo) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_org.py#L16)):*
> ```Python
>         assert org.get('name') == self.config['vcd']['org_name']
> 
>     def test_02_update_enable_org(self):
> ```

test_02_enable_org() is good enough :)

---

*[tests/vcd_org.py, line 22 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZifUg0Kj_vkBNi5ao:-L-ZifUg0Kj_vkBNi5ap:b-kx7yes) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_org.py#L22)):*
> ```Python
>         self.assertTrue(updated_org['IsEnabled'])
> 
>     def test_03_update_disable_org(self):
> ```

test_03_disable_org() is good enough :)

---

*[tests/vcd_user.py, line 51 at r2](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZXKhHxqthvqjeOjbR:-L-ZjXzWEsx_EQXlRtcp:b32v57) ([raw file](https://github.com/anusuyar/pyvcloud/blob/4a5d8ad610183922f0960df5e3bd3a8f215aece9/tests/vcd_user.py#L51)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

updated_user is the task returned by api call, right? How does updated_user['IsEnabled'] return boolean? Am I missing something :)
</blockquote></details>

+1

---

*[tests/vcd_user.py, line 24 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Zj3vhvLKpb_kGzkPr:-L-Zj3vhvLKpb_kGzkPs:brfwvyg) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_user.py#L24)):*
> ```Python
>         org = Org(self.client, resource=logged_in_org)
>         result = org.delete_user(user_name)
>         print(result)
> ```

Don't print things in the helper function, let the printing happen in the actual test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 495 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Zg41JK-xcZzdeUZuI:-L-b1m1sPoqqzAZWtMTH:bp55lwg) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/pyvcloud/vcd/org.py#L495)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

If the above if checks have failed, we would be doing an unnecessary PUT call, we should avoid that.
</blockquote></details>

Agreed. Also please specify the type of is_enabled (string or bool)

---

*[pyvcloud/vcd/system.py, line 91 at r1](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Y3zMtORM19ayKi23u:-L-b3Wx0gOyNLqK35xgq:bazvg1) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2f34b61839081fa2cf7fffd286bc7c523e5e1e4c/pyvcloud/vcd/system.py#L91)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think we should a more generic version of the function. Something like get_admin_href() which can take any href, replace /api/ to /api/admin/
</blockquote></details>

`get_admin_href` in utils seems like a good suggestion

---

*[tests/vcd_org.py, line 1 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZiHfNT7ovOeBNxCx7:-L-b3pdU16jiYKCep39s:b2ufo6o) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_org.py#L1)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Shouldn't we add the vmware copyright headers to test files too?
</blockquote></details>

yes, let's add the copyright headers

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6)*

**Comment by anusuyar** [comment]
Review status: 1 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 495 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Zg41JK-xcZzdeUZuI:-L-d5yRg9V1a5aBdL8LL:bs7wumx) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/pyvcloud/vcd/org.py#L495)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

Agreed. Also please specify the type of is_enabled (string or bool)
</blockquote></details>

Done. 

---

*[pyvcloud/vcd/org.py, line 650 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZgGnYIFMAAoQPc7dR:-L-d6-dJrca65HVRzzhi:b-896fix) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/pyvcloud/vcd/org.py#L650)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Same as the comment above for update_user, we shouldn't be initiating a no-op PUT request
</blockquote></details>

Done.

---

*[pyvcloud/vcd/system.py, line 91 at r1](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Y3zMtORM19ayKi23u:-L-d710bNK80jTTm3h12:b-f491lg) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2f34b61839081fa2cf7fffd286bc7c523e5e1e4c/pyvcloud/vcd/system.py#L91)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

`get_admin_href` in utils seems like a good suggestion
</blockquote></details>

Done.  added get_admin_href()

---

*[pyvcloud/vcd/utils.py, line 60 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZhlDdspn6gk1Go45z:-L-d7drlCoVYyW-UV-pW:bjqo6re) ([raw file](https://github.com/anusuyar/pyvcloud/blob/a3e991fdbd806d23fe8f385d07d362c68ae5eeb6/pyvcloud/vcd/utils.py#L60)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Probably you would want to run flake8 from command line on this file. I think the added indentation will trigger a warning.
</blockquote></details>

There is no flake8 warning for these lines.

---

*[pyvcloud/vcd/utils.py, line 323 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZhvcJ3XNSVXpQm8Z0:-L-d7mybI-0mRLhSiUlk:b-896fix) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/pyvcloud/vcd/utils.py#L323)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

As I stated earlier we should have a more generic version of this function. Otherwise the current form of the function belongs to Org.py as pointed out by Paco.
</blockquote></details>

Done.

---

*[tests/vcd_org.py, line 1 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZiHfNT7ovOeBNxCx7:-L-d8-iGy2umaFugZkB0:b-896fix) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_org.py#L1)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

yes, let's add the copyright headers
</blockquote></details>

Done.

---

*[tests/vcd_org.py, line 16 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZiXz7R0e11blH1Bnx:-L-d86RQ8SFQa41abAsc:b-896fix) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_org.py#L16)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

test_02_enable_org() is good enough :)
</blockquote></details>

Done.

---

*[tests/vcd_org.py, line 22 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZifUg0Kj_vkBNi5ao:-L-d86jRASfQEHBW-IFK:b-896fix) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_org.py#L22)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

test_03_disable_org() is good enough :)
</blockquote></details>

Done.

---

*[tests/vcd_user.py, line 51 at r2](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-ZXKhHxqthvqjeOjbR:-L-d8QPscl8h1YAlfZDS:bc07t1g) ([raw file](https://github.com/anusuyar/pyvcloud/blob/4a5d8ad610183922f0960df5e3bd3a8f215aece9/tests/vcd_user.py#L51)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

+1
</blockquote></details>

update_user returns the updated user object. Not the task. 

---

*[tests/vcd_user.py, line 24 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Zj3vhvLKpb_kGzkPr:-L-d8JJlii6GhlzPi7TB:b-nfes7j) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_user.py#L24)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Don't print things in the helper function, let the printing happen in the actual test
</blockquote></details>

Done.  Removed the print statement. I don't think we need printing in the tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r2, 1 of 1 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-:-L-hAEHZNfhHXfWm6YTX:bnfp4nl)*

**Comment by rocknes** [comment]
Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 644 at r4](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-hXnMJ5j8XvArs-j5a:-L-hXnMJ5j8XvArs-j5b:bijhfon) ([raw file](https://github.com/anusuyar/pyvcloud/blob/e5c917a7ca24b2970e953f76e2368e133f7f04d6/pyvcloud/vcd/org.py#L644)):*
> ```Python
>         """  # NOQA
>         org = self.client.get_org_by_name(org_name)
>         org_href = get_admin_href(org.get('href'))
> ```

nit: since the resources involved are admin type, probably we should name the variables accordingly e.g.  org_admin_href, org_admin_resource etc.

---

*[pyvcloud/vcd/utils.py, line 326 at r4](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-hYEYDNP-c6-1f4Sk8:-L-hYEYDNP-c6-1f4Sk9:bb7dmtm) ([raw file](https://github.com/anusuyar/pyvcloud/blob/e5c917a7ca24b2970e953f76e2368e133f7f04d6/pyvcloud/vcd/utils.py#L326)):*
> ```Python
> 
> def get_admin_href(href):
>     return href.replace('/api/',
> ```

What happens if the input string doesn't have '/api/' in it? Do we return the original string back or do we throw an exception?

---

*[tests/vcd_user.py, line 24 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Zj3vhvLKpb_kGzkPr:-L-hZ-RU8NERayYz12Kc:bgpbkiy) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_user.py#L24)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Done.  Removed the print statement. I don't think we need printing in the tests.
</blockquote></details>

Umm how are we making sure that the delete call went through successfully?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6)*

**Comment by anusuyar** [comment]
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[pyvcloud/vcd/org.py, line 644 at r4](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-hXnMJ5j8XvArs-j5a:-L-hgnSoP612G4ydrGlA:b-896fix) ([raw file](https://github.com/anusuyar/pyvcloud/blob/e5c917a7ca24b2970e953f76e2368e133f7f04d6/pyvcloud/vcd/org.py#L644)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

nit: since the resources involved are admin type, probably we should name the variables accordingly e.g.  org_admin_href, org_admin_resource etc.
</blockquote></details>

Done.

---

*[pyvcloud/vcd/utils.py, line 326 at r4](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-hYEYDNP-c6-1f4Sk8:-L-heDop2BuYNJTFRMNu:b-h14ld5) ([raw file](https://github.com/anusuyar/pyvcloud/blob/e5c917a7ca24b2970e953f76e2368e133f7f04d6/pyvcloud/vcd/utils.py#L326)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

What happens if the input string doesn't have '/api/' in it? Do we return the original string back or do we throw an exception?
</blockquote></details>

it will just return the original string.

---

*[tests/vcd_user.py, line 24 at r3](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-L-Zj3vhvLKpb_kGzkPr:-L-hfDRtN6rrFa00vpJ5:bwh24gi) ([raw file](https://github.com/anusuyar/pyvcloud/blob/2ec188137e46dd1a04088f37c877d816a3c4f6ca/tests/vcd_user.py#L24)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Umm how are we making sure that the delete call went through successfully?
</blockquote></details>

The delete_resouce will throw an exception when the request fails.

    def _do_request(self,
                    method,
                    uri,
                    contents=None,
                    media_type=None,
                    accept_type=None,
                    objectify_results=True):
        response = self._do_request_prim(method,
                                         uri,
                                         self._session,
                                         contents=contents,
                                         media_type=media_type)
        sc = response.status_code

        if 200 <= sc <= 299:
            return _objectify_response(response) if objectify_results else \
                etree.fromstring(response.content)

        if 400 <= sc <= 499:
            raise VcdErrorResponseException(
                sc,
                self._get_response_request_id(response),
                objectify.fromstring(response.content))

        raise Exception("Unsupported HTTP status code (%d) encountered" % sc)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6)*

**Comment by rocknes** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/6#-:-L-i42COd32AMqqgc_HQ:bnfp4nl)*

**Pull request closed without merging**
