### PR TITLE
Removed org_name in the update_org

### PR DESCRIPTION
**Pull request by anusuyar**
Removed org_name in the update_org.
Since we are going to create a new method reload org. Not updating self.resource after updating
the org.

### CODE REVIEW

**Comment by anusuyar** [comment]
This change is [Reviewable](https://reviewable.io/reviews/anusuyar/pyvcloud/7)

**Comment by pacogomez** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/org.py, line 633 at r1](https://reviewable.io:443/reviews/anusuyar/pyvcloud/7#-L-n5OdHjumJNoaFDI3n:-L-n5OdHjumJNoaFDI3o:b-jj5h0k) ([raw file](https://github.com/anusuyar/pyvcloud/blob/abf03aaebf94372e0adc9e84327a3f4b955dedc4/pyvcloud/vcd/org.py#L633)):*
> ```Python
>             if hasattr(org_admin_resource, 'IsEnabled'):
>                 org_admin_resource['IsEnabled'] = E.IsEnabled(is_enabled)
>                 return self.client.put_resource(self.href_admin,
> ```

does this return a long running task embedded in the org resource?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/7)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/org.py, line 633 at r1](https://reviewable.io:443/reviews/anusuyar/pyvcloud/7#-L-n5OdHjumJNoaFDI3n:-L-n7KQBRmSTDQt02zXU:b-s37rh4) ([raw file](https://github.com/anusuyar/pyvcloud/blob/abf03aaebf94372e0adc9e84327a3f4b955dedc4/pyvcloud/vcd/org.py#L633)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

does this return a long running task embedded in the org resource?
</blockquote></details>

No. it does not return any task in the org resource.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/7)*

**Comment by pacogomez** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pyvcloud/vcd/org.py, line 633 at r1](https://reviewable.io:443/reviews/anusuyar/pyvcloud/7#-L-n5OdHjumJNoaFDI3n:-L-n7geA71x9sUC3gE2N:b-25sd4h) ([raw file](https://github.com/anusuyar/pyvcloud/blob/abf03aaebf94372e0adc9e84327a3f4b955dedc4/pyvcloud/vcd/org.py#L633)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

No. it does not return any task in the org resource.
</blockquote></details>

ok, then it makes sense the return values

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/7#-:-L-n8KiXFH81w9eRnflf:bnfp4nl)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/anusuyar/pyvcloud/7#-:-L-nEMRbp-lH_hSDyRpQ:bnfp4nl)*

**Pull request closed without merging**
